### ISSUE TITLE
Learn Boxen

### ISSUE THREAD

**Issue by sb2nov** [sb2nov/mac-setup#1]
Learn boxen to create a boxen instead of the long setup.

**Comment by acafourek** [comment]
:+1:

**Comment by potherca** [comment]
@sb2nov So... you're going to add a pull-request outlining _how_, right?

**Comment by sb2nov** [comment]
Yes will do. It has been a while since I played around with it. If anyone wants to contribute something here please do.

**Comment by sb2nov** [comment]
Closing as if I do this it'll be part of a different project.
