### ISSUE TITLE
Automate installs?

### ISSUE THREAD

**Issue by runnickrun** [sb2nov/mac-setup#100]
Great guide!
Newbie question, though: is it possible to automate some of the stuff, e.g. put it in the file and then process installs one by one?

**Comment by runnickrun** [comment]
Already found: you can do it via install.sh file

**Comment by pi-ron** [comment]
@runnickrun Can you please provide a bit more info on how you automated the guide?

**Comment by runnickrun** [comment]
Sure, though I haven't researched it deeper yet. 
As far as I understand, you can write shell commands in a script file for shell (e.g., install.sh) and then execute this file from your terminal.

Here is one example: [https://github.com/nil84/install.sh/blob/master/install-python27.sh](https://github.com/nil84/install.sh/blob/master/install-python27.sh) **I'm not sure if it's for Mac. 

You can try to search for install.sh examples on GitHub, and to narrow your search try looking for something like "Day One Install". 

Hope that helps.
