### ISSUE TITLE
Add ZSH with prezto: no such file or directory: /Users/*****/Projects/config/env.sh

### ISSUE THREAD

**Issue by gavingk** [sb2nov/mac-setup#107]
-zsh

install prezto: after with this step:

edit the .zshrc by opening the file in a text editor and adding the following below
     # Add env.sh
    source ~/Projects/config/env.sh

Iterm2 prompt:
Users/gavin/.zshrc:source:14: no such file or directory: /Users/gavin/Projects/config/env.sh

what's wrong with the config?  thxs.
<img width="648" alt="screen shot 2017-01-23 at 3 43 43 pm" src="https://cloud.githubusercontent.com/assets/13556360/22195420/dcc53fe0-e182-11e6-8110-09e7697aac64.png">
<img width="642" alt="screen shot 2017-01-23 at 3 44 05 pm" src="https://cloud.githubusercontent.com/assets/13556360/22195419/dcc3cbb0-e182-11e6-8ad0-30d797ea79ef.png">

**Comment by sb2nov** [comment]
The zsh instructions page also has the env.sh file at the end. http://sourabhbajaj.com/mac-setup/iTerm/zsh.html 

We create a different file as that lets you write custom functions, check it in separately from your shell.
