### ISSUE TITLE
config zsh + iterm

### ISSUE THREAD

**Issue by yonilip** [sb2nov/mac-setup#115]
First of all thanks for the setup guide! Its really well written and helped me setup quickly :)

I was recently irritated by the fact that when activating a virtualenv source, the terminal wouldnt write under what env im running, so I decided to revisit your guide.

After following the Iterm2 + Zsh steps in your guide, every time I open iterm I get the following:

```
Last login: Thu Mar 16 19:07:06 on ttys000
Usage: prompt <options>
Options:
    -c              Show currently selected theme and parameters
    -l              List currently available prompt themes
    -p [<themes>]   Preview given themes (defaults to all)
    -h [<theme>]    Display help (for given theme)
    -s <theme>      Set and save theme
    <theme>         Switch to new theme immediately (changes not saved)

Use prompt -h <theme> for help on specific themes.
MacBook-Pro%
```

.zshrc:
```
#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

ZSH_THEME=pygmalion

plugins=(git colored-man colorize github jira vagrant virtualenv pip python brew osx zsh-syntax-highlighting)

# Add env.sh
source ~/Projects/config/env.sh
```

env.sh:

```
#!/bin/zsh

# PATH
export PATH="/usr/local/share/python:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export EDITOR='subl -w'
# export PYTHONPATH=$PYTHONPATH
# export MANPATH="/usr/local/man:$MANPATH"

# Virtual Environment
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Projects
source /usr/local/bin/virtualenvwrapper.sh

# Owner
export USER_NAME="YOUR NAME"
eval "$(rbenv init -)"

# FileSearch
function f() { find . -iname "*$1*" ${@:2} }
function r() { grep "$1" ${@:2} -R . }

#mkdir and cd
function mkcd() { mkdir -p "$@" && cd "$_"; }

# Aliases
alias cppcompile='c++ -std=c++11 -stdlib=libc++'

# Use sublimetext for editing config files
alias zshconfig="subl ~/.zshrc"
alias envconfig="subl ~/Projects/config/env.sh"

```

something must be failing to show this. color is only applied to the input im writing in the terminal..

Any idea what might be wrong?

**Comment by sb2nov** [comment]
R: @sb2nov tagging self so I can remember to look into this over the weekend.

**Comment by yonilip** [comment]
Found the problem. I installed both oh-my-zsh and prezto (newbie mistake!)

I guess I didnt see that you wrote in the ZSH section that we will install one of them. at the top of the page, it indicates that we will install oh-my-zsh but then prezto is offered which might be misleading, especially for people who arent familiar with these frameworks and their meaning.

**Comment by sb2nov** [comment]
@yonilip Completely agree, let me make that clearer

**Comment by sb2nov** [comment]
Updated the guide so closing the issue.
