### ISSUE TITLE
Docker section recommends deprecated version installation

### ISSUE THREAD

**Issue by shanmoon** [sb2nov/mac-setup#119]
Docker has been supported natively for awhile now. Doctor toolbox is no longer the recommended way to run Docker on Macs.

**Comment by sb2nov** [comment]
@shanmoon agreed, I had left a similar comment on https://github.com/sb2nov/mac-setup/pull/108. Would it be possible for you to create a PR for this ?

**Comment by sb2nov** [comment]
Just saw your PR that fixed this.
