### ISSUE TITLE
Add ST3 to LaTeX editors (LaTeXTools)

### ISSUE THREAD

**Issue by Kyslik** [sb2nov/mac-setup#123]
I can not stress enough that ST3 is best editor for LaTeX of course with the ultimate tool that makes it great https://github.com/SublimeText/LaTeXTools

I can make a PR but should I include LaTeXTools in SublimeText packages or in LaTeX section.

Yay #123 :)

**Comment by sb2nov** [comment]
A PR for this would be great, I think we can add it to both as people might come to the different pages directly.

Thank you for the help 👍
