### ISSUE TITLE
Possible typo in brew reset section

### ISSUE THREAD

**Issue by naman** [sb2nov/mac-setup#124]
I think there is a possible typo in the brew reset section, I think by `cd /usr/local` you mean `cd /usr/local/Homebrew/`. People new to git may face problems here.

<img width="867" alt="screen shot 2017-06-29 at 12 07 17 pm" src="https://user-images.githubusercontent.com/5255299/27674497-a940632c-5cc3-11e7-9231-fb725a5e2089.png">

**Comment by sb2nov** [comment]
Thanks
