### ISSUE TITLE
Include ack?

### ISSUE THREAD

**Issue by simeg** [sb2nov/mac-setup#131]
@sb2nov What's your opinion on using [`ack`](https://beyondgrep.com/)? I'm using since pretty recently and I think it's a lot better than any other code search command I've tried. For a quick introduction I'd recommend [the video on this page](https://beyondgrep.com/why-ack/).

If you think it's a good idea I could do the writing. Let me know what you think.

**Comment by sb2nov** [comment]
This would be great, I think we can also include a link to the silver searcher [ag](https://github.com/ggreer/the_silver_searcher) which I use as a replacement for ack.

Thank you for the PR in advance 👍

**Comment by MacgyverMartins** [comment]
+1
