### ISSUE TITLE
Add stubs for lazy people (.gitignore...)

### ISSUE THREAD

**Issue by Kyslik** [sb2nov/mac-setup#135]
### Example

So lets say I want to configure `.gitignore` http://sourabhbajaj.com/mac-setup/Git/gitignore.html

Lets have an option for lazy people to simply copy/paste command to download file instead of manually creating it...

```
curl -O https://github.com/sb2nov/mac-setup/tree/master/git/stubs/.gitignore
```
>**Note**: curl should be installed on every O SX since Lion

There are two options how to do this: 
 - have master stubs folder and *host* all files there
 - let each section (eg: `/git`, `/zsh`...) have its own stubs folder

**Comment by sb2nov** [comment]
How about we just provide a command that leverages the code already checked into https://github.com/github/gitignore as we'll be duplicating a lot of what is already being maintained in this repo. Thoughts?

**Comment by Kyslik** [comment]
I didnt even know that repository exists :)

do you mean like including link for https://github.com/github/gitignore/blob/master/Global/macOS.gitignore ?
