### ISSUE TITLE
Visual Studio Code maybe?

### ISSUE THREAD

**Issue by Kyslik** [sb2nov/mac-setup#143]
There is a sublime-text section, perhaps VSCode could be one as well, not sure if many people use it but its one of those fast ones.

**Comment by sb2nov** [comment]
+1, also as it is free while sublime is paid so it might be good for the readers.

In my experiments I found VSCode much faster than Atom at startup so liked it a bit more.

**Comment by Kyslik** [comment]
Exactly my "would be" arguments for VSCode.

**Comment by simeg** [comment]
Will close this in favor of #154.
