### ISSUE TITLE
MySQL section is missing in master

### ISSUE THREAD

**Issue by simeg** [sb2nov/mac-setup#148]
It looks like it went missing in [this commit](https://github.com/sb2nov/mac-setup/commit/48a98c2822589ddd07e7383f71089a88533c0f78). 

Is there a reason why it went missing? Not sure if I understand the latest commit messages.

**Comment by sb2nov** [comment]
I may have screwed something up. For some reason MySQL in the URL wasn't working on github pages so I was experimenting around changing the directory name. I'll fix it in sometime. 

Thanks for catching. The gh-pages branch seems to have it.

**Comment by sb2nov** [comment]
Fixed, btw I also removed the search bar otherwise it shows a warning about the page not being served via https
