### ISSUE TITLE
Remove unused files

### ISSUE THREAD

**Issue by simeg** [sb2nov/mac-setup#153]
Looking through the files in the root folder there seems to be a few files that are not being used. `book.epub` and `book.json` were added in a commit with message `fix links and update grunt-gitbook`. And they haven't been updated in 3 years. Can we remove them?

Also, are you using the Grunt commands? I see `Gruntfile.js` has a few commands but are you using them? I would really like to remove them because I'm having issues installing packages related to grunt, which I cannot seem to resolve which annoys me :P But if you are using them we should keep them and I'll try some more to resolve the issues.

**Comment by simeg** [comment]
Reading up on Gitbook I realised `book.json` is necessary for it to run. So we should not remove that file then.

**Comment by sb2nov** [comment]
Fixed now in 774b0a751a312e76c0bc5ed5421b8a07315158ae

**Comment by simeg** [comment]
@sb2nov What about the Gruntfile? Do you know if it's being used? Maybe we can remove it now that we have the Makefile :)

**Comment by sb2nov** [comment]
I'll remove it as I think the makefile is sufficient
