### ISSUE TITLE
Use CI tool for build status

### ISSUE THREAD

**Issue by simeg** [sb2nov/mac-setup#162]
I think it would be cool to use Travis (or any other CI tool, but I really like Travis) to know the build status for each PR and each merge to master. I imagine it running `gitbook build` on every PR and if that command fails we know that we should fix it before merging it. I use this for all my projects and it improves my confidence when merging PRs.

If you think it's a good idea you're the only person who can setup the Travis connection @sb2nov, as you're the owner of this repo.

**Comment by Kyslik** [comment]
I like Travis too, does building fail often? (I do not build this on my local machine).

**Comment by sb2nov** [comment]
I have rarely seen it fail unless the markdown itself is wrong, but that is easy to check if you use any markdown editor. Regardless we should set it up as a best practice I think.

**Comment by simeg** [comment]
Great. Then I'm leaving you as single assignee to this issue then @sb2nov as it requires action on your side.

**Comment by simeg** [comment]
Any update on this @sb2nov? I don't mind doing the configuration if you just set up the project. The build failed for me when changing some configuration, so I'd feel safer to have CI setup :)

**Comment by sb2nov** [comment]
Sorry didn't get time last week but have sent you a PR for this now.
