### ISSUE TITLE
Unify OS name macOS vs OS X

### ISSUE THREAD

**Issue by Kyslik** [sb2nov/mac-setup#164]
Creating issue from discussion which can be seen in the end of #159.

**Comment by simeg** [comment]
```
$ ack -i "macos"
Git/gitignore.md
30:Or simply download [**macOS** specific .gitignore](https://github.com/github/gitignore/blob/master/Global/macOS.gitignore) maintained by GitHub itself and put contents of it to `~/.gitignore`.
34:>curl https://raw.githubusercontent.com/github/gitignore/master/Global/macOS.gitignore -o ~/.gitignore

Homebrew/README.md
2:[Homebrew](https://brew.sh/) calls itself _The missing package manager for **macOS_** and is an essential tool for any developer.

iTerm/README.md
22:### **MacOS** shortcuts ⌘←, ⌘→ and ⌥←, ⌥→

Xcode/README.md
2:[Xcode](https://developer.apple.com/xcode/) is an integrated development environment for **macOS** containing a suite of software development tools developed by Apple for developing software for **macOS**, iOS, watchOS and tvOS.
13:XQuartz is Apple Inc.'s version of the X server, a component of the X Window System for **macOS**. It might be useful if you are developing software for **macOS**, it's available for download [here](http://xquartz.macosforge.org/landing/).
```

For the homebrew occurrence (_The missing package manager for macOS_) I don't think we should change it as it's a quote taken from their website.

**Comment by hugovk** [comment]
I would vote for the name macOS:

* macOS is the current of the OS. If you get a new computer from Apple, and want to set it up using this guide, the guide should match Apple's terminology.
* OS X was the old name. People still use it, but in formal use, a guide should use the most up-to-date names. Onwards and upwards!
* macOS has some 156 000 000 Google results
* OS X has about 143 000 000 Google results
* Top Google results for macOS are generally for pages with macOS in the title
* Top Google results for OS X are generally for pages with macOS in the title
* Following Homebrew's lead isn't necessarily a bad thing, given how popular it is with developers, and with this guide also (as the number 2 thing to install: called "an essential tool for any developer"). https://github.com/Homebrew/brew/issues/961 is their issue discussing the rename, including these reasons for rename:

  * > As Apple Inc. has renamed the desktop operating system from OS X to macOS, these diagnostic information will confuse people as time goes on, especially for the new-generation developers who learn developing from macOS 10.12.
  * > I'm increasingly of the opinion that we should take the simplest route, avoid code complexity, and replace all instances of “Mac OS X” and “OS X” with a static “macOS” (and be done). I cannot imagine there will be much confusion and people (at least our target audience) will figure it out quickly.
  *  > The API reference at https://developer.apple.com/reference/ only ever speaks of “macOS” when talking about when an API was introduced, even if it's “macOS 10.0+”.

**Comment by Kyslik** [comment]
I agree here with @hugovk, apple calls the OS MacOS so should this book. Google numbers are irrelevant I guess.

(I am myself using OS X no matter what, because its shorter)

**Comment by simeg** [comment]
Ok I'm cool with using macOS :) Those are good reasons, consistency is what I want. Feel free to change my PR, or I change it when I get time to.

**Comment by hugovk** [comment]
Here's a new PR: #170.
