### ISSUE TITLE
New Auto Build Tool

### ISSUE THREAD

**Issue by corbanb** [sb2nov/mac-setup#182]
### I'm Submitting a Tool for automating the setup process
```
[ ] Bug report
[x] Tool/language/etc documentation request
```

### Tool/Language/etc
https://github.com/corbanb/osx-developer-setup

My hope is this tool will be shared to get others involved and make the guide you are building easier than ever for engineers.

**Comment by simeg** [comment]
Hi @corbanb.

I like your project, if designed correctly it could be very useful :) However I'm not sure if this is the place for a tool that is very opinionated and (by the looks of the many uncompleted TODOs) far from completed. There's no agreed philosophy for this repo but I see it as a source of information useful for setting up your dev environment. Your tool is basically replacing any use for this repo in an opinionated way.

Those are the reasons why I don't think your tool should be part of this repo. I hope I am making sense and that you understand my reasoning. Maybe in the future when the tool is more sophisticated and lets the user decide on it's own, it could have it's own section here ⭐️ 

Will close this now and if someone thinks differently just re-open it.
