### ISSUE TITLE
[BUG] Source *.md differs from the built html

### ISSUE THREAD

**Issue by Kyslik** [sb2nov/mac-setup#186]
https://github.com/sb2nov/mac-setup/blob/master/Homebrew/Cask.md

is different from 

http://sourabhbajaj.com/mac-setup/Homebrew/Cask.html

---

To be exact:

[App suggestions - source](https://github.com/sb2nov/mac-setup/blob/master/Homebrew/Cask.md#app-suggestions) and [App suggestions - html (not linkable)](http://sourabhbajaj.com/mac-setup/Homebrew/Cask.html)

Any ideas?

**Comment by simeg** [comment]
I don't understand, where do they differ? In my browser they look the same. Maybe caching issue on your end?

Screenshots would be 🔝 notch.

**Comment by Kyslik** [comment]
I just busted cache using dev tools and it still persists. The whole files is just different.

Here screenshots:

**[md file](https://github.com/sb2nov/mac-setup/blob/master/Homebrew/Cask.md#app-suggestions)**

![source](https://user-images.githubusercontent.com/2067589/34637866-a7a02646-f2bf-11e7-8796-a6b87de249d7.PNG)

**[rendered html](http://sourabhbajaj.com/mac-setup/Homebrew/Cask.html)**

![screen shot 2018-01-06 at 8 56 48 am](https://user-images.githubusercontent.com/2067589/34637875-d76bc43e-f2bf-11e7-81bd-6f431f0dc5c2.PNG)

**Comment by simeg** [comment]
That is weird. I just cleared my cache as well and it looks fine for me.

![image](https://user-images.githubusercontent.com/8566054/34639604-403419bc-f2e3-11e7-9471-0bfddf186bb6.png)

**Comment by Kyslik** [comment]
Ok, on incognito mode it works fine and I can see "App Suggestions" instead of "App Installation", but when I bust cache using chrome dev tools -> "empty cache and hard reload" nothing happens it loads a bit slower but with "App Installation" content (old one). See video below.
![cask](https://user-images.githubusercontent.com/2067589/34639902-160979c4-f2e9-11e7-8486-29227d631acb.gif)

**Comment by Kyslik** [comment]
Something is really weird... I can not bust the cache from browser at the same time browsers shows me that it just downloaded Cask.html so it should be brand new.

When I curl the page it has same effect as using incognito mode I get "correct" content with App Suggestions.

```sh
➜  mac-setup git:(improve-iterm2) curl http://sourabhbajaj.com/mac-setup/Homebrew/Cask.html | grep "App Installation"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22395  100 22395    0     0  10499      0  0:00:02  0:00:02 --:--:-- 10504
➜  mac-setup git:(improve-iterm2) curl http://sourabhbajaj.com/mac-setup/Homebrew/Cask.html | grep "App Suggestions"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22395  100 22395    0     0  52992      0 --:--:-- --:--:-- --:--:-- 53068
<h2 id="app-suggestions">App Suggestions</h2>
```

---

## SOLVED

I had to do "nuclear reset" 💣 , chrome dev tools -> application tab -> clear everything.
