### ISSUE TITLE
Update repo description

### ISSUE THREAD

**Issue by simeg** [sb2nov/mac-setup#189]
### I'm Submitting a ...

```
[x] Bug report
[ ] Tool/language/etc documentation request
```

### Bug Location
The repo description says "_Installing Development environment on Mac OS X_" but we decided to use the term "_macOS_" instead of "_OS X_". So I think we should update this.

Assigning to @sb2nov because only owners can change the description.

**Comment by Kyslik** [comment]
(suggestion) topic changes/additions:

- guide
- guidebook
- macos
- fresh-installs

**Comment by sb2nov** [comment]
Done. Thanks.
