### ISSUE TITLE
Add Stronghold to Security section

### ISSUE THREAD

**Issue by alichtman** [sb2nov/mac-setup#199]
### I'm Submitting a ...

```
[ ] Bug report
[x] Tool/language/etc documentation request
```
### Tool/Language/etc

[stronghold](https://github.com/alichtman/stronghold) -- The easiest way to securely configure MacOS.

**Comment by sb2nov** [comment]
Thanks for sharing this really useful project. Would you mind creating a PR for adding this?

**Comment by alichtman** [comment]
Opened.
