### ISSUE TITLE
add: sdkman to manage java versions

### ISSUE THREAD

**Issue by ndeitch** [sb2nov/mac-setup#201]
### I'm Submitting a ...

```
[ ] Bug report
[X] Tool/language/etc documentation request
```

### Tool/Language/etc

Hey,

I'm a Java Developer, and I use [sdkman](http://sdkman.io/) to manage Java versions (and other [sdks](http://sdkman.io/sdks.html)).

Do you think that is valuable add this config on Java setup or in a different topic?

If so, I'll be pleasure to make a pr.

**Comment by simeg** [comment]
I think it sounds useful, go for it!

**Comment by kamleshkc2002** [comment]
This has been fixed and will be available on the website once the new gitbook release is deployed
