### ISSUE TITLE
homebrew/science was deprecated

### ISSUE THREAD

**Issue by sslees** [sb2nov/mac-setup#202]
### I'm Submitting a ...

```
[ ] Bug report
[x] Tool/language/etc documentation request
```

### Bug Location

http://sourabhbajaj.com/mac-setup/Python/numpy.html
The command `brew tap homebrew/science` results in:
```
Error: homebrew/science was deprecated. This tap is now empty as all its formulae were migrated.
```

#### Other Information

_PS. This site is a fantastic resource!_

**Comment by Kyslik** [comment]
Lots homebrew taps were moved to core, we should do a sweep.

- https://github.com/sb2nov/mac-setup/blob/8b5cd133bb2d542c4696157c4df891a257775446/Apps/Octave.md
- https://github.com/sb2nov/mac-setup/search?utf8=%E2%9C%93&q=tap&type=

**Comment by sb2nov** [comment]
+1 to ^

**Comment by simeg** [comment]
@sb2nov Since you're the owner you'd have to configure Travis (it's simple - just adding a cron job to a specific branch) and add the status badge from it to the README. I'll create a PR for it soon.

**Comment by simeg** [comment]
Closing as issue is fixed
