### ISSUE TITLE
Badge table looks bad with gitbook

### ISSUE THREAD

**Issue by simeg** [sb2nov/mac-setup#210]
### I'm Submitting a ...

```
[x] Bug report
[ ] Tool/language/etc documentation request
```

### Bug Location

![image](https://user-images.githubusercontent.com/8566054/40326371-47e5adf8-5d3f-11e8-8095-71dc04f77709.png)

### Tool/Language/etc
Reproduce by running `make serve` and go to `http://localhost:4000/`

### Other Information
Looks like gitbook can ignore files, but not code snippets or similar. Not sure how to fix this.

**Comment by hugovk** [comment]
Perhaps the syntax for tables is stricter with GitBook than GitHub.

https://toolchain.gitbook.com/syntax/markdown.html#tables shows pipe symbols on the header line too:

```
| First Header  | Second Header |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell  |
```

**Comment by simeg** [comment]
Fixed in https://github.com/sb2nov/mac-setup/commit/ae3db58dbdf64b33c31afc5aeca097887d48730b.

It now looks like this:

![image](https://user-images.githubusercontent.com/8566054/40329866-597d81ec-5d4b-11e8-907f-0868037e5591.png)
