### ISSUE TITLE
Install source code pro font with brew

### ISSUE THREAD

**Issue by Beasta** [sb2nov/mac-setup#218]
### I'm Submitting a ...

```
[] Bug report
[x] Tool/language/etc documentation request
```

### Other Information
Source code pro can be install with brew. saves a lot of time:

Homebrew (macOS)
```
brew tap caskroom/fonts && brew cask install font-source-code-pro
```
https://github.com/adobe-fonts/source-code-pro

**Comment by simeg** [comment]
Nice. I think we should just change the download section for that font to use brew. PRs are more than welcome!

**Comment by simeg** [comment]
Fixed in b900664e15c2bbabe10c92a5fcd34289445bf5a9.

**Comment by prabhugopal** [comment]
`brew tap homebrew/cask-fonts && brew cask install font-source-code-pro`
worked for me

**Comment by the-vampiire** [comment]
thanks @prabhugopal i had to make a small adjustment because of a conflicting fonts set to

```sh
$ brew tap homebrew/cask-fonts && brew cask install homebrew/cask-fonts/font-source-code-pro 
```

**Comment by ListenLove** [comment]
Thanks!

**Comment by mattconway1984** [comment]
> `brew tap homebrew/cask-fonts && brew cask install font-source-code-pro`
> worked for me

I tried the above suggestion, it didn't work, but brew suggested I run:
`brew cask install font-source-code-pro`
Which worked for me.

**Comment by jasnzhuang** [comment]
at 2021-1-27
now we should use this:
`brew Tap homebrew/cask-fonts && brew install --cask font-source-code-pro`

**Comment by bazilsafronov** [comment]
> 

Error: Unknown command: cask

**Comment by sprive** [comment]
2022-07-13
FYI the above no longer works

```
Mac-mini:head-first-c sprive$ brew Tap homebrew/cask-fonts && brew install --cask font-source-code-pro
==> Tapping homebrew/cask-fonts
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts'...
remote: Enumerating objects: 61410, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 61410 (delta 19), reused 28 (delta 15), pack-reused 61371
Receiving objects: 100% (61410/61410), 11.80 MiB | 15.57 MiB/s, done.
Resolving deltas: 100% (45440/45440), done.
Tapped 1959 casks (1,992 files, 14.7MB).
Warning: Calling depends_on :macos => :yosemite is deprecated! There is no replacement.
Please report this issue to the homebrew/cask-versions tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions/Casks/keyboard-maestro8.rb:10

Error: Calling Cask::DSL::Version#before_colon is disabled! Use Cask::DSL::Version#csv instead.
Please report this issue to the homebrew/cask-versions tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions/Casks/dotnet-preview.rb:6
```

**Comment by juji** [comment]
this works:

`brew tap homebrew/cask-fonts && brew install --cask font-source-code-pro`

**Comment by a1nkur** [comment]
@juji Your command does not work anymore. Here is the `Error: homebrew/cask-fonts was deprecated. This tap is now empty and all its contents were either deleted or migrated.`
