### ISSUE TITLE
Contribution Template link not working

### ISSUE THREAD

**Issue by mariobeka** [sb2nov/mac-setup#225]
### I'm Submitting a ...

```
[x] Bug report
[ ] Tool/language/etc documentation request
```

### Bug Location

When trying to access the _contribution template_ link from the following web-page
https://sourabhbajaj.com/mac-setup/
a **404 Not Found Error** is shown.

**Comment by simeg** [comment]
Fixed in: https://github.com/sb2nov/mac-setup/commit/77f88fe41e8a0221ae843a7ed3c5d9da80638348
