### ISSUE TITLE
Typos in System Preferences

### ISSUE THREAD

**Issue by lantran** [sb2nov/mac-setup#226]
### I'm Submitting a ...

```
[x] Bug report
[ ] Tool/language/etc documentation request
```

### Bug Location

First of all, thanks for writing this tutorial. I followed your tutorial and saw some typos in **System Preferences**
* `$ brew install homebrew/fuse/ntfs-3g` should change to `$ brew install ntfs-3g`
* At ***step 7*, `$ csrutil disable` should change to `$ csrutil enable`

**Comment by sb2nov** [comment]
This is already fixed. I redeployed the website just incase.

**Comment by lantran** [comment]
Confirmed. Thanks @sb2nov. I learn a lot thru your blog :)
