### ISSUE TITLE
betterzipql no longer brewable

### ISSUE THREAD

**Issue by DannyDannyDanny** [sb2nov/mac-setup#227]
### I'm Submitting a ...
```
[ ] Bug report
[x] Tool/language/etc documentation request (**update**)
```

### Bug Location
Cask for `betterzipql` no longer exists.
<img width="514" alt="screenshot 2018-10-23 at 17 02 55" src="https://user-images.githubusercontent.com/16453674/47370250-9cb89f00-d6e5-11e8-80fb-8cd827e1fa50.png">

**Comment by simeg** [comment]
@DannyDannyDanny Thanks. Would you mind submitting a PR for it? :) And maybe find out where to get that package.

**Comment by lukasmalkmus** [comment]
Related:
https://github.com/sindresorhus/quick-look-plugins/issues/78
https://macitbetter.com/BetterZip-Quick-Look-Generator/

**Comment by DannyDannyDanny** [comment]
@simeg I'll be brutally honest and say this is my first real issue submission. I'm not sure what a PR is 😅
