### ISSUE TITLE
Docker installation having issues in Mac through brew

### ISSUE THREAD

**Issue by anirudhagar13** [sb2nov/mac-setup#232]
### I'm Submitting a ...

```
[ x] Bug report
[ ] Tool/language/etc documentation request
```

### Bug Location

Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
 
#### Steps to recreate bug:
1. brew cask install docker-toolbox
2. docker run hello-world
3. sudo docker-compose build

### Other Information

Found resolution at : https://docs.docker.com/docker-for-mac/install/ 
(Apparently, this is the recommended way by many to install dockers for Mac).

**Comment by kamleshkc2002** [comment]
This issue can be closed now

**Comment by hugovk** [comment]
Thanks!

Tip: Let's use the magic "fixes #xxx" in PRs on the future, to autoclose issues.

https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue
