### ISSUE TITLE
Running sudo without specifying password each time

### ISSUE THREAD

**Issue by worldofprasanna** [sb2nov/mac-setup#236]
### I'm Submitting a ...

```
[ ] Bug report
[X] Tool/language/etc documentation request
```

### Tool/Language/etc

Typing password for sudo commands would be pain at times. Because there would be multiple softwares to install and each and everytime we should enter the password.
### Other Information
Modify the sudoers file and implicitly trust the mac user as sudo user.

**Comment by simeg** [comment]
Closing this because of reasons specified in #237.
