### ISSUE TITLE
Make gh-pages branch proteced

### ISSUE THREAD

**Issue by simeg** [sb2nov/mac-setup#243]
Because we're serving the guide from the gh-pages branch we should mark it as protected, so it doesn't get accidentally removed.

Assigning @sb2nov because only you can make this change.

**Comment by sb2nov** [comment]
Great idea. Done.

**Comment by simeg** [comment]
Opening this up again because I'm unable to deploy.

```
...
remote: error: GH006: Protected branch update failed for refs/heads/gh-pages.
remote: error: At least 1 approving review is required by reviewers with write access.
To github.com:sb2nov/mac-setup.git
 ! [remote rejected] gh-pages -> gh-pages (protected branch hook declined)
error: failed to push some refs to 'git@github.com:sb2nov/mac-setup.git'
```

Looking at the settings I think this checkbox needs to be unticked:
> - [ ] Require pull request reviews before merging

I think it's enough to just have it as a protected branch (without ticking any of the checkboxes), that will prevent force pushes and accidental deletion.

**Comment by sb2nov** [comment]
Thanks. Fixed it.
