### ISSUE TITLE
MySql Route Error

### ISSUE THREAD

**Issue by dlionz** [sb2nov/mac-setup#244]
### I'm Submitting a ...
```
[x] Bug report
[ ] Tool/language/etc documentation request
```

### Bug Location
The [MySql](https://sourabhbajaj.com/mac-setup/MySQL/ ) route on the gitbook does not resolve to anything. I receive a 404 when I go there. However I can view it from the Github Repo Directly.

Possibly related to Issue #148

**Comment by dlionz** [comment]
I forked the repo and cloned it down and when I run it localy the MySQL route resolves as expected. not sure why its not working on the live version

**Comment by simeg** [comment]
Thanks @dlionz!

Should we revert #224? I remember this being a problem before.

**Comment by sb2nov** [comment]
@simeg seems like the exact issue we were seeing before and that is why we made the intentional typo in the URL.

**Comment by simeg** [comment]
Reverted in e0419165f5443938ef52c4b3317716ff7d0bea35. Let's not allow this to be changed back until we've figured out the actual problem.
