### ISSUE TITLE
Homebrew Cask has been folded back in to core Homebrew

### ISSUE THREAD

**Issue by apjanke** [sb2nov/mac-setup#254]
### I'm Submitting a ...
```
[X] Bug report
[ ] Tool/language/etc documentation request
```

### Bug Location

http://sourabhbajaj.com/mac-setup/Homebrew/Cask.html

### Tool/Language/etc

The Homebrew Cask section talks about Caskroom and Cask being a separate add-on for Homebrew. This is no longer the case; Cask support [has been folded into core Homebrew](https://github.com/Homebrew/homebrew-cask/issues/14384) and is now installed with all Homebrew installations.

This section could be condensed down to just some suggestions of particular Casks to install (and maybe a description of what makes a Cask different from a regular Homebrew formula). There's no longer any need for Cask-specific setup.

**Comment by kamleshkc2002** [comment]
+1 

The command `brew tap caskroom/cask` points to a deprecated tap. It has been replaced with `brew tap homebrew/homebrew-cask` (not that you need this since cask is already integrated).

**Comment by sb2nov** [comment]
@apjanke @kamleshkc2002 would be great if you want to take a shot at upgrading this and send a PR.

**Comment by kamleshkc2002** [comment]
This looks like this has been fixed by this commit: 6694c5b02ba46d229e66eebde7394e5c772dc233
