### ISSUE TITLE
Error: Cask 'totalfinder' is unavailable: No Cask with this name exists.

### ISSUE THREAD

**Issue by raheemazeezabiodun** [sb2nov/mac-setup#256]
### I'm Submitting a ...

```
[-] Bug report
[ ] Tool/language/etc documentation request
```

### Bug Location

![Uploading Screenshot 2019-07-17 at 1.10.47 PM.png…]()

### Other Information

This error pops up when running

```
brew cask install \
    alfred \
    android-file-transfer \
    asepsis \
    appcleaner \
    caffeine \
    cheatsheet \
    docker \
    doubletwist \
    dropbox \
    google-chrome \
    google-drive \
    google-hangouts \
    flux \
    latexian \
    1password \
    pdftk \
    spectacle \
    sublime-text \
    superduper \
    totalfinder \
    transmission \
    valentina-studio \
    vlc
```

It's not just `totalfinder` that's unavailable, these are the lists of apps
```asepsis, google-drive, latexian, pdftk, totalfinder```
If this can also be confirmed by someone else, I can raise a pr to remove them

**Comment by simeg** [comment]
Thanks! Fixed in https://github.com/sb2nov/mac-setup/commit/e62d3b1754baabc8927d920e971fe11f1b717b6a
