### ISSUE TITLE
Let's stop requesting minor edits from contributors

### ISSUE THREAD

**Issue by simeg** [sb2nov/mac-setup#266]
Hi!

Awesome seeing good activity on this project :) I can see on Google Analytics that we had 25k active users in August compared to 21k last year. We got 7 PRs the last month which is one every 4.3 days!

I think we can make the experience of contributing even better by stop requesting minor edits to PRs. With Github you can edit the PR in your browser and hence reduce the time and roundtrips to improving the guide. I think this is fairly new because I just recently found it 😄

![image](https://user-images.githubusercontent.com/8566054/64472666-58e65100-d162-11e9-8085-85c411a5cfb4.png)

By minor changes I mean changes about spelling or stylistic changes (e.g. `MacOS` -> `macOS`).

WDYT? @sb2nov @Kyslik @hugovk

**Comment by sb2nov** [comment]
Great idea. Let's do it :D

**Comment by simeg** [comment]
Awesome! Everyone seems to agree so I'm closing this :)
