### ISSUE TITLE
“MacVim” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by Beeohat** [sb2nov/mac-setup#271]
### I'm Submitting a ...

```
[ ] Bug report
[ ] Tool/language/etc documentation request
```

**Comment by simeg** [comment]
Hi @Beeohat. 

I don't understand what this issue means. I can't find any references to `MacVim` in the repository.

Can you expand on the problem/question?

**Comment by Beeohat** [comment]
Thanks for the prompt response. The MacVim is a text editor app, which I since have discovered how to open. Thanks again.
