### ISSUE TITLE
Outdated information in numpy section

### ISSUE THREAD

**Issue by denkk0** [sb2nov/mac-setup#277]
### I'm Submitting a ...

```
[x] Bug report
[ ] Tool/language/etc documentation request
```

### Bug Location

http://sourabhbajaj.com/mac-setup/Python/numpy.html

### Tool/Language/etc

The `Homebrew formulae` repo does not exist.

**Comment by kamleshkc2002** [comment]
just verified this. Brew is not even the correct way of installing these libraries anymore. Waiting for a separate PR to get merged. Will work on this post that.

**Comment by kamleshkc2002** [comment]
This issue can be closed now
