### ISSUE TITLE
Should the main branch be renamed to `main` instead of `master`

### ISSUE THREAD

**Issue by kamleshkc2002** [sb2nov/mac-setup#298]
### I'm Submitting a ...

```
[ ] Bug report
[X ] Tool/language/etc documentation request
```

### Other Information
With most of the repositories moving to rename the branch `master` to `main`, i think we should also follow suit. If agreed upon, i can work on this.

**Comment by simeg** [comment]
Sounds good to me! Not sure how much you can do without proper access to the repo but please give it a go. I don't think anyone would disagree to changing it.

**Comment by kamleshkc2002** [comment]
yep, i cannot do much without having repo permissions. the least i can do is update the code references but someone has to clone the `master` branch into `main` branch.

**Comment by hugovk** [comment]
Let's get https://github.com/sb2nov/mac-setup/pull/299 merged first, then we can, in this order:

* [ ] branch `master` to `main`
* [ ] @sb2nov changes the default branch from `master` to `main` at https://github.com/sb2nov/mac-setup/settings/branches

Then in any order:

* [ ] Update code references to `master `in `main` branch
* [ ] Update code references to `master `in `health-check` branch
* [ ] Delete `master` branch

Finally:

* [ ] Make sure deploys work

**Comment by kamleshkc2002** [comment]
these steps definitely make sense..

once the first 2 steps are complete, i can start on the rest

**Comment by simeg** [comment]
Ping @sb2nov 🏓

**Comment by sb2nov** [comment]
Just updated the default branch, thank you so much for driving this :D

**Comment by simeg** [comment]
I just verified that the deploy works. Great job everyone!
