### ISSUE TITLE
Move from Gitbook to Docsify

### ISSUE THREAD

**Issue by kamleshkc2002** [sb2nov/mac-setup#303]
### I'm Submitting a ...

```
[ ] Bug report
[x ] Tool/language/etc documentation request
```

### Bug Location
N/A

### Tool/Language/etc
N/A

### Other Information
With gitbook support diminishing and it moving to a pay to use model, i was wondering if moving to docsify makes more sense. I have already done the changes but need some help with the hosting part.

Further, this reduces a lot of dependencies and makes the website much lighter to load

https://docsify.js.org/#/quickstart

**Comment by hugovk** [comment]
I've not been following changes about GitBook. At least https://www.gitbook.com/pricing says:

> GitBook is free for open-source & non-profit teams
> Open-source & non-profits make the world a better place, providing software & services to those in need. We would love to play our part and help you build great docs!

Which is quite common for code services (CI, etc.). 

Please could you expand a bit on how support is diminishing?

**Comment by kamleshkc2002** [comment]
hmm interesting. Some of the teams that i work with actively started moving out of Gitbook just because they wanted to move on before Gitbook stopped becoming free.. If Gitbook continues being non-free then its not worth the change. Thanks for the helpful comment as always Hugo!
