### ISSUE TITLE
Health Check failing due to 503 for one of the links

### ISSUE THREAD

**Issue by 21CSM** [sb2nov/mac-setup#304]
### I'm Submitting a ...
```
[x] Bug report
[ ] Tool/language/etc documentation request
```

### Bug Location
https://sourabhbajaj.com/mac-setup/Apps/

### Other Information
Seems that Black Pixel, the company that created Kaleidoscope, has been acquired by another company (Hypergiant). Due to this, the Kaleidoscope webpage is not being maintained and the link in the guide results in a 503 error. This is causing the health check to fail. 

Suggestion is to link to [Mac App Store](https://apps.apple.com/us/app/kaleidoscope/id587512244).

[Link to broken travis build](https://travis-ci.org/github/sb2nov/mac-setup/builds/716219961)

**Comment by simeg** [comment]
Thanks @21CSM! I merged you PR.
