### ISSUE TITLE
Add: Live Server and vscode-icons (Visual Studio Code)

### ISSUE THREAD

**Issue by Clifton893** [sb2nov/mac-setup#307]
### I'm Submitting a ...
```
[ ] Bug report
[x] Tool/language/etc documentation request
```

### Tool/Language/etc
Hello, as a **Visual Studio Code** user, I'd like to add two useful extensions to the Visual Studio Code subsection:
- [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer)
- [vscode-icons](https://marketplace.visualstudio.com/items?itemName=vscode-icons-team.vscode-icons)

Each extension has over 5 million downloads, and I can attest to their critical utility in my VSCode workflow. Let me know if you agree, and I'll be happy to make a PR!

**Comment by simeg** [comment]
Sounds good to me!

**Comment by simeg** [comment]
Fixed in #308.
