### ISSUE TITLE
Anaconda

### ISSUE THREAD

**Issue by duemme** [sb2nov/mac-setup#331]
Hi, I'm not a developer. I'm just trying to learn python.
I installed brew and using brew I installed python 3.9 and some other packages.
Now I would like to start projects using pandas and other data analysis libraries.
I'm really confused on how to procede.
Anaconda seems the best solution but I don't know if installing anaconda could create a mess with brew.
What do you suggest?
After installing Anaconda I should use a virtual environment for each new project?
thanks

**Comment by simeg** [comment]
Hi @duemme.

This is not the best place to ask for support questions. I recommend the [chat of StackOverflow](https://chat.stackoverflow.com/) for such questions. There's a python room where people will be able to help!
