### ISSUE TITLE
Ruby: build failed when installing 2.7.0 

### ISSUE THREAD

**Issue by careylzh** [sb2nov/mac-setup#348]
### I'm Submitting a ...

```
[ ] Bug report
[x] Tool/language/etc documentation request
```

### Bug Location

When running `rbenv install 2.7.0`
<img width="913" alt="Screenshot 2022-02-09 at 10 01 26 PM" src="https://user-images.githubusercontent.com/10573919/153216497-08b10a20-a933-4f06-a305-818ea5b2a5b1.png">

Issue was solved through `export optflags="-Wno-error=implicit-function-declaration"` (see https://github.com/TaKO8Ki/frum/issues/97)

### Tool/Language/etc

Ruby installation

**Comment by otkd** [comment]
@simeg should be able to close this as well, thanks
