### ISSUE TITLE
google-hangouts is no longer available for installation

### ISSUE THREAD

**Issue by WHFF521** [sb2nov/mac-setup#372]
### I'm Submitting a suggestion

```
[x] Bug report
```

### Bug Location
[Homebrew/Cask.md](https://github.com/sb2nov/mac-setup/blob/4dc77cc4ed05921f980152fc05c513aaf469b605/Homebrew/Cask.md)
### bug information
today I try to execute the order in the file above. But something went wrong.
```
 ➜  ~ brew install --cask google-hangouts
==> Downloading https://formulae.brew.sh/api/cask.jws.json
#=O#-   #      #
Warning: Cask 'google-hangouts' is unavailable: No Cask with this name exists.
==> Downloading https://formulae.brew.sh/api/formula.jws.json
#=O#-   #      #
==> Searching for similarly named casks...
==> Casks
google-chat

To install google-chat, run:
  brew install --cask google-chat
```
It seems like there isn't a cask named google-hangouts available in the Homebrew Cask repository. Google Hangouts might not be distributed as a cask through Homebrew.  
So If possible, please replace or remove 'google-hangouts' in the installation command.

**Comment by hugovk** [comment]
Google Hangouts no longer exists: 

* https://killedbygoogle.com/
* https://arstechnica.com/gadgets/2022/06/google-hangouts-finally-gets-a-shutdown-date-november-2022/

Would you like to open a PR to remove it?
