### ISSUE TITLE
License question...

### ISSUE THREAD

**Issue by potherca** [sb2nov/mac-setup#42]
As I recal, MIT (and other software licenses) only partain the _software documentation_, not written prose.

Because this is a body of work that contains written word and not _software_, shouldn't it have a different license than the MIT License? There are [several options for documentation licenses](http://www.dreamsongs.com/IHE/IHE-50.html) available.

**Comment by sb2nov** [comment]
Do you think `FreeBSD Documentation License` is good here. I want to let people use this however they want and just make sure they cite this as a reference.

**Comment by sb2nov** [comment]
@potherca ping ^

**Comment by potherca** [comment]
Sorry for not responding sooner. Somehow this fell of my radar.

In the beginning of open-source software, there weren't any "open doc" licenses, so various organisations created their own. Nowadays, the [Creative Commons](http://creativecommons.org/) licenses are the most readily used licenses for "open" written word and/or documentation.

For example: 

- StackOverflow uses the [CC-WIKI or CC-BY-SA license](CC BY-SA) for text (and MIT for code) <sup>[source](http://blog.stackoverflow.com/2009/06/attribution-required/)</sup>
- Wikipedia dual licenses under the [CC BY-SA] and the [GNU Free Documentation License](https://en.wikipedia.org/wiki/GNU_Free_Documentation_License) (GFDL)
<sup>[source](https://en.wikipedia.org/wiki/Wikipedia:Copyrights)</sup>

If you need more examples, I can dig around for more, but the general jest will be the same.

For the contents of this repo, I would suggest using the [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/).

That license states the following :

- Freedom to copy and redistribute the material in any medium or format.
- Appropriate credit must be given (provide a link to the license, and indicate if changes were made) 
- Freedom to remix, transform, or build upon the material, for any purpose, even commercially, as long as those changes are placed under the same license

If you are unsure if this is a good enough match to what you want, I would advise to fill out the [license picker at Creative Commons](https://creativecommons.org/choose/).

[CC BY-SA]: https://creativecommons.org/licenses/by-sa/3.0/

**Comment by sb2nov** [comment]
Thanks @potherca I updated the license. Really appreciate the detailed explanation and help here.
