### ISSUE TITLE
Ruby installation problem

### ISSUE THREAD

**Issue by HammenWS** [sb2nov/mac-setup#61]
When I try to to install ruby through homebrew with the following command

    brew install rbenv ruby-build rbenv-gem-rehash rbenv-default-gems

It can't find the formulas for rbenv-gem-rehash and rbenv-default-gems.
Do I need to do something before installing these?

**Comment by sb2nov** [comment]
@HammenWS rbenv-gem-rehash is deprecated so i updated the docs to remove that. 

did you try `brew update` before installing `rbenv-default-gems`
