### ISSUE TITLE
Cask instructions are no longer needed

### ISSUE THREAD

**Issue by jballer** [sb2nov/mac-setup#62]
Cask is now included in the Homebrew repo ([Source](https://github.com/caskroom/homebrew-cask)), so the Cask instructions should be updated to just point to Homebrew install instructions.

I came across this while setting up Vagrant; I don't have time to open a PR now since I'd want to ensure that I don't break links elsewhere in the site.

**Comment by sb2nov** [comment]
@jballer thanks for reporting, I updated the installation instructions as the rest should remain the same.

**Comment by jballer** [comment]
Awesome. Thanks for putting this book together :+1:
