### ISSUE TITLE
Ruby : add references to rbenv-gemset

### ISSUE THREAD

**Issue by ValentinTrinque** [sb2nov/mac-setup#68]
Rbenv is a great tool for handling ruby version and gem versioning. Gems tends to add up quickly when your work on several project. A good way to not poluate your machine with thousand of package rbenv-gemsets came to life.

Here is the link : https://github.com/jf/rbenv-gemset

It would be nice to add a reference to this package. 

What do you think ?

**Comment by sb2nov** [comment]
@ValentinTrinque would you be able to submit a PR with the changes. I'm not a heavy ruby user so only know the basics.

**Comment by ValentinTrinque** [comment]
Here it is :D

**Comment by sb2nov** [comment]
Thanks 👍
