### ISSUE TITLE
Question: How easy is it to start over?

### ISSUE THREAD

**Issue by barronlroth** [sb2nov/mac-setup#69]
I get a ton of issues in Brew Doctor and installing things in Python. How difficult is it to reset my entire dev environment?

**Comment by johandry** [comment]
I setup my dev environment in Vagrant or Docker so when I screw it up I don't have to reset my laptop. 
When I didn't use any of them was a pain every time I had to reinstall everything.

**Comment by evanfuture** [comment]
For mac preferences and such, look into dotfiles.  This is a good starting place:  https://github.com/mathiasbynens/dotfiles

The idea is, you have as much of your preferences saved as possible so that reinstalling the OS isn't such a daunting thought.

**Comment by sanketss84** [comment]
@johandry  so when you set in docker is it like a sandbox or virtual machine kinda thing. I am sorry am not much aware of the concept of docker. can you please a little bit more or point me a good article or youtube link which explains this in a short simple manner. thanks.

**Comment by sb2nov** [comment]
brew uninstall is a good way to start again. Like several ppl mentioned here using docker also is a good place to experiment around.
