### ISSUE TITLE
Scala guide: Updating sbtopts command has issues with newline characters

### ISSUE THREAD

**Issue by dgrizzanti** [sb2nov/mac-setup#82]
It appears that this command causes issues with sbt:
```$ echo '-J-XX:+CMSClassUnloadingEnabled\n-J-Xmx2G\n' >> /usr/local/etc/sbtopts```

At least, it did when I used it. sbt would complain at run time:
```
$ sbt
Unrecognized VM option 'CMSClassUnloadingEnabledn-J-Xmx2Gn'
Did you mean '(+/-)CMSClassUnloadingEnabled'?
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

This was due to the two options being added on a single line with newline characters instead of being separated by newlines.

With current command:
```
# java version (default: java from PATH, currently $(java -version |& grep version))
#
#-java-home <path>

-J-XX:+CMSClassUnloadingEnabled\n-J-Xmx2G\n
```

How I think it should read:
```
# java version (default: java from PATH, currently $(java -version |& grep version))
#
#-java-home <path>

-J-XX:+CMSClassUnloadingEnabled
-J-Xmx2G
```

**Comment by dgrizzanti** [comment]
Page for reference, http://sourabhbajaj.com/mac-setup/Scala/README.html

**Comment by csaltos** [comment]
Just activate the `echo` command escaping option `-e` like this:

```bash
echo -e '-J-XX:+CMSClassUnloadingEnabled\n-J-Xmx2G\n' >> /usr/local/etc/sbtopts
```

And you should be good to go
