### ISSUE TITLE
updating env.sh

### ISSUE THREAD

**Issue by nhsmith85** [sb2nov/mac-setup#83]
Sourabh, 
I really like your website. Have a question about how to edit the env.sh. Following your directions here: http://sourabhbajaj.com/mac-setup/iTerm/zsh.html but you lose me at the end. How do you access the env.sh to edit and update? thanks!

**Comment by Nilegfx** [comment]
I've the exact same challenge since I am new to mac!

**Comment by sb2nov** [comment]
@nhsmith85 @Nilegfx https://github.com/sb2nov/mac-setup/blob/master/iTerm/zsh.md#envsh has the details of the env.sh

You can add the file anywhere. I just put in a config folder in Project for myself. Please feel free to edit the zsh.md file if you think we can make the guide clearer. Also happy to accept more contributions.
