### ISSUE TITLE
Where is "~/.zpreztorc"

### ISSUE THREAD

**Issue by pascalandy** [sb2nov/mac-setup#84]
In
https://github.com/sb2nov/mac-setup/blob/master/iTerm/zsh.md

I have to:
edit the ~/.zpreztorc file and add

I have no idea where this is. What ~ means ??

In my path: 
/Users/p_andy/.zprezto

I list those files:
drwxr-xr-x  14 p_andy  staff   476 14 Jul 21:57 .git
-rw-r--r--   1 p_andy  staff    36 14 Jul 21:57 .gitignore
-rw-r--r--   1 p_andy  staff  1034 14 Jul 21:57 .gitmodules
-rw-r--r--   1 p_andy  staff  1619 14 Jul 21:57 CONTRIBUTING.md
-rw-r--r--   1 p_andy  staff  3588 14 Jul 21:57 README.md
-rw-r--r--   1 p_andy  staff  2901 14 Jul 21:57 init.zsh
drwxr-xr-x  42 p_andy  staff  1428 14 Jul 21:57 modules
drwxr-xr-x   9 p_andy  staff   306 14 Jul 21:57 runcoms

I just need a bit more details here :)
Thanks!

**Comment by sb2nov** [comment]
if you do `ls -la /Users/p_andy` you should be able to see it I think.

**Comment by pascalandy** [comment]
Great! Thank you!
