### ISSUE TITLE
Sublime Text Package: How do I find the latest version

### ISSUE THREAD

**Issue by pascalandy** [sb2nov/mac-setup#88]
from : http://sourabhbajaj.com/mac-setup/SublimeText/Packages.html

Thank you!

**Comment by sb2nov** [comment]
https://packagecontrol.io/installation is the way to install the package manager and after that all packages are I think auto updated similar to chrome.

**Comment by sb2nov** [comment]
@pascalandy I'm going to close this, feel free to reopen if you need any help.
