### ISSUE TITLE
What to do with env.sh ?

### ISSUE THREAD

**Issue by pascalandy** [sb2nov/mac-setup#89]
on page - http://sourabhbajaj.com/mac-setup/iTerm/zsh.html

I don't know where I should put this config

## env.sh

```
#!/bin/zsh

    # PATH
    export PATH="/usr/local/share/python:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export EDITOR='subl -w'
    # export PYTHONPATH=$PYTHONPATH
    # export MANPATH="/usr/local/man:$MANPATH"

    # Virtual Environment
    export WORKON_HOME=$HOME/.virtualenvs
    export PROJECT_HOME=$HOME/Projects
    source /usr/local/bin/virtualenvwrapper.sh

    # Owner
    export USER_NAME="YOUR NAME"
    eval "$(rbenv init -)"

    # FileSearch
    function f() { find . -iname "*$1*" ${@:2} }
    function r() { grep "$1" ${@:2} -R . }

    #mkdir and cd
    function mkcd() { mkdir -p "$@" && cd "$_"; }

    # Aliases
    alias cppcompile='c++ -std=c++11 -stdlib=libc++'

    # Use sublimetext for editing config files
    alias zshconfig="subl ~/.zshrc"
    alias envconfig="subl ~/Projects/config/env.sh"
```

Then the guide refers to it again on the Python section and I'm still clueless. 

Thanks!

---

EDIT: I put it there /Users/my-name/Project_Demo/config

Make sense ?

**Comment by pascalandy** [comment]
on page - http://sourabhbajaj.com/mac-setup/Python/README.html

I'm completely lost on this:

> Save the file and open a new terminal to take the new $PATH into account (everytime you open a terminal, .bash_profile gets loaded).

**Comment by yacevedo** [comment]
Every time you open a zsh terminal, it will run .zshrc
If you followed the instructions, you will have added the following line to .zshrc
```
# Add env.sh
source ~/Projects/config/env.sh
```

What that means is that .zshrc will look for env.sh in that file location and run it.

"Save the file" just means save env.sh if you haven't already so all the changes are recorded.

This os x guide is not just follow steps 1-10 and you are done. If you don't know what is happening each step, try to spend some time thinking about what is happening and maybe google some terminology. This guide assumes a little terminal and linux knowledge.

**Comment by yacevedo** [comment]
See [](http://hacktux.com/bash/bashrc/bash_profile) for some basic info on .bash_profile. It is loaded every time a terminal is opened (except for a few cases you probably don't have to worry about). .zshrc is the analogous file for zsh, which you are using if you followed this guide.

Feel free to google things if you don't know what is happening.

**Comment by pascalandy** [comment]
I guess the only thing I missed was the fake Project_Demo part. It was not clear to me. Else than that it's great!

**Comment by sb2nov** [comment]
Thanks @yacevedo for resolving this. @pascalandy feel free to make changes if you think we can make some parts of the guide easier to read and understand. Always welcoming contributions.

**Comment by amygeojo** [comment]
do you create the env.sh file yourself?I followed the directions above (http://sourabhbajaj.com/mac-setup/iTerm/zsh.html) as well. The other files listed were auto-generated

**Comment by sb2nov** [comment]
@amygeojo I create it manually as that lets me keep the autogenerated files clean while I set the environment variables / alias / functions I want without depending on the shell being used as I can source it with `!bash` even when using zsh.

**Comment by sandradc** [comment]
@sb2nov where do you put the file though ? `~/env.sh` ?

**Comment by sb2nov** [comment]
@sandradc in the $HOME directory. Just do `vi ~/env.sh` to start it
