### ISSUE TITLE
If you completed this guide, say thanks here!

### ISSUE THREAD

**Issue by pascalandy** [sb2nov/mac-setup#90]
Here is the place to say thank you to folks who are working hard on this project.

« One of the greatest ways to show your appreciation to open source projects you enjoy is to open an issue that let people say thank you »

_Disclaimer: I don't have any kind of connexion or personal interest with maintainers(s) of this project. Pure gratitude here._

Cheers!

**Comment by pascalandy** [comment]
It's the 2nd mac I'm configuring thanks to this guide and I believe we should say out loud "Thank you".

Cheers!

**Comment by sb2nov** [comment]
Thanks 👍

**Comment by abrkn** [comment]
Thanks! :+1:

**Comment by raavanan** [comment]
Thanks 👍

**Comment by beibei-l** [comment]
Thanks 👍

**Comment by andela-cdike** [comment]
Thanks a lot.

**Comment by Bohdan-Anderson** [comment]
Amazing,

**Comment by pi-ron** [comment]
Thanks, it's brilliant!  Configured two macs now using this guide and recommend it to coworkers 👍

**Comment by rogermedia** [comment]
Thank you!

**Comment by patrickbreidenbach** [comment]
Thank you!

**Comment by andersonbarutti** [comment]
Thank you!

**Comment by Switchxa** [comment]
Thanks, appreciate having a new bible.

**Comment by kshitij10496** [comment]
@sb2nov I recently got my first Mac and I feel really lucky to stumble across this guide.
It helped me setup and running within an hour.
Thanks a lot for this !
Let me know if you need any help maintaining this guide. I would be more than happy to contribute.

**Comment by sb2nov** [comment]
@kshitij10496 Sure, if you see anything that is outdated or missing. Please file issues or create a PR as you see fit.

**Comment by BSCowboy** [comment]
@sb2nov Thanks for throwing this all together.

**Comment by 3fernandez** [comment]
Thank You. 👍

**Comment by etiennemtl** [comment]
Very nice & complete guide! It gets you set up for a real developer environment with the best tools around. Just a minor suggestion, would be nice to add jenv for the Java part. Jenv is a version management tool for java just like rbenv for ruby. The only difference is that you have to download the different version manually. Cheers

**Comment by sb2nov** [comment]
@etiennemtl that is a great idea. Would you be able to create a PR for that ?

**Comment by sb2nov** [comment]
@etiennemtl Whenever you have time should work fine.

**Comment by xavierartot** [comment]
thx

**Comment by KartoshkaD** [comment]
Thanks, really
I was trying to build my own steps but then found this repo and now I'm happy

**Comment by SithEngineer** [comment]
Thank you very much. Keep up the good work!

**Comment by it-ailen** [comment]
Thanks you. 👍

**Comment by ar4mirez** [comment]
Thanks o much I love it. 👍

**Comment by Morganvd** [comment]
This guide is a god sent to me I use it everytime 
Thanks a mil

**Comment by webmurkser** [comment]
Many thanks!

**Comment by vlaw** [comment]
Many thanks, great job!

**Comment by davebeach** [comment]
Many thanks, as my new mac now is starting off with everything organized and done the right way.

**Comment by Jethro87** [comment]
This guide was a big help. Thanks so much!

**Comment by naman** [comment]
Thanks for the guide!

**Comment by iandrewt** [comment]
Amazing guide, thanks 👍

**Comment by yannux** [comment]
Great guide for a fresh install ! Thanks 👍

**Comment by QianXuX** [comment]
Thanks! Just started and LOVE the guide

**Comment by sb2nov** [comment]
Thanks it is all thanks to the work from some amazing friends such as @simeg @Kyslik etc.

**Comment by vnbrs** [comment]
I wanna marry this repo.

**Comment by sslees** [comment]
Fantastic guide! Thanks for putting this together and for compiling such a great collection of setup tips.

**Comment by TamarIS** [comment]
thanks!!

**Comment by shreyasbharath** [comment]
Thanks! This really is an amazing guide for developers new to Macs.

**Comment by Beasta** [comment]
Game changer! i learned mucho!

**Comment by kamleshkc2002** [comment]
Thanks! amazing collaboration from the contributors as well who keep track of the issues and update the documentation as well.

**Comment by apjanke** [comment]
Okay, I haven't said "👍" here yet, but I have used and liked this guide, so, "👍👍👍!!!" Kudos to all involved, and especially to Sourabh (@sb2nov) for marshalling all this enthusiasm and work.

Keep it comin', y'all!

**Comment by awadhwana** [comment]
Thank you for such a detailed guide ((:

**Comment by andrydella** [comment]
Thank you for sich a nice guide :)

**Comment by pascalandy** [comment]
Closing simply to stop seeing it in Raycast :-p
